### ISSUE TITLE
Client display styles overridden/broken by page

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/client#244]
This is a consolidation of a number of reported issues which all seem to be the result of either:

1. page styles overriding the expected styling of Hypothesis client UI
2. page security policy (such as CSP) preventing the correct rendering of Hypothesis client UI

As they all likely have a common fix, I'm putting the multiple examples and bug reports all in one issue so we can more easily track possible solutions and eventual fixes.

### Original bugs

- hypothesis/client#84
- hypothesis/client#235
- hypothesis/h#1848
- hypothesis/h#2444
- hypothesis/h#3136

#### 1. Global `<button>` styles:

Global `<button>` and `<ul>` styles cause the toolbar buttons to be displayed incorrectly.

Example: http://ccc.coastal.edu/index.php/task/102-badge-3-2/ 

CSS:

```css
button, html input[type="button"] {
    opacity: .2;
}
```

Screenshot:

![](https://cloud.githubusercontent.com/assets/1413074/18193202/267231d4-7090-11e6-8656-58453c85d2db.png)

#### 2. Global `<ul>` styles with `!important`

Global `<ul>` styles cause the toolbar buttons to be offset "under" the sidebar frame.

Example: http://speakingjs.com/es5/ch14.html

CSS:

```css
ul {
    list-style-type: square;
    margin-top: 8px !important;
    margin-bottom: 8px !important;
    margin-left: 5px !important;
    padding-left: 20px !important;
}
```

#### 3. Global `<div>` styles (1)

Global div styles cause the entire sidebar to be displayed offscreen to the bottom right of the page.

Example: http://roots.cx/

CSS:

```css
#index>div {
    position: relative;
}
```

Screenshot:

![](https://camo.githubusercontent.com/24a58b1758633454707a991e65f7b93c5a98e0aa/68747470733a2f2f63646e2e706272642e636f2f696d616765732f32466f6a4a66744d2e706e67)

#### 4. Global `<div>` styles (2)

Global div styles cause a new page element to appear when activating the sidebar.

Example: http://example.com/ (really!)

CSS:

```css
div {
    width: 600px;
    margin: 5em auto;
    padding: 50px;
    background-color: #fff;
    border-radius: 1em;
}
```

#### 5. Page CSP prevents toolbar icon font loading correctly:

**N.B.** you need to use the _bookmarklet_ to see this problem, as the extension circumvents the issue by loading assets from the `chrome-extension://...` origin.

Examples:
- https://medium.com/@idarosesylvester/when-your-cousin-is-the-supreme-court-nominee-e966f709a41e#.51qhwbwly
- https://backchannel.com/a-gourmet-guide-to-wifi-b9a308e662a9#.asa9xlpzv

(Both of these are Medium sites).

CSP header:

```
Content-Security-Policy: 
    default-src 'self'; 
    connect-src https://localhost https://*.instapaper.com https://*.stripe.com https://getpocket.com https://backchannel.com https://*.backchannel.com https://*.medium.com https://medium.com https://*.medium.com https://*.algolia.net https://cdn-static-1.medium.com https://dnqgz544uhbo8.cloudfront.net https://*.lightstep.com 'self'; 
    font-src data: https://*.amazonaws.com https://*.medium.com https://*.gstatic.com https://dnqgz544uhbo8.cloudfront.net https://use.typekit.net https://cdn-static-1.medium.com 'self'; 
    frame-src chromenull: https: webviewprogressproxy: medium: 'self'; 
    img-src blob: data: https: 'self'; 
    media-src https://*.cdn.vine.co https://d1fcbxp97j4nb2.cloudfront.net https://d262ilb51hltx0.cloudfront.net https://*.medium.com https://gomiro.medium.com https://miro.medium.com https://pbs.twimg.com 'self'; 
    object-src 'self'; 
    script-src 'unsafe-eval' 'unsafe-inline' about: https: 'self'; 
    style-src 'unsafe-inline' data: https: 'self'; 
    report-uri https://csp.medium.com
```

Screenshots:
![](https://cloud.githubusercontent.com/assets/24781335/23094433/c083d56e-f5c6-11e6-8751-989a6f48524e.png)
![screen shot 2017-02-21 at 12 30 18](https://cloud.githubusercontent.com/assets/3602/23163142/946cd508-f831-11e6-9856-9703dbf718cd.png)
![screen shot 2017-02-21 at 12 31 07](https://cloud.githubusercontent.com/assets/3602/23163187/a73e45ae-f831-11e6-9872-fb8888eacb89.png)
